((lambda()
  (call-with-current-continuation 
   (lambda(cont)
     (for-each (lambda(e)
                 (if (< e 3)
                     (begin (display e) (newline))
                     (cont e)
                  ))
               '(1 2 3 4 5))))
  (display "--end--")
  (newline)
  ))

(define (foobar)
  (let (
        (n 0)
        (saved #f))
    (call-with-current-continuation (lambda(ctx)(set! saved ctx) (ctx 0)))
    (display n)
    (newline)
    (set! n (+ n 1))
    saved))
(display "--begin test--")
(newline)
(define (a) (foobar))
(a 0)
(display "--end test--")
(newline)
                                   